api_currencies:
  path: /api/currencies
  controller: App\Controller\DefaultController::currencies

api_currency:
  path: /api/currency/{currency}/{startDate}/{endDate}
  controller: App\Controller\DefaultController::currency

index:
  path: /
  defaults: {
    _controller: App\Controller\DefaultController::index
  }
  requirements:
    wildcard: .*
