services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/App'

  App\Controller\:
    resource: '../src/App/Controller'
    autowire: true
    tags: ['controller.service_arguments']
